server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  tomcat:
    max-http-post-size: 20000
    max-http-form-post-size: 20000
    max-http-header-size: 20000
  datasource:
      hikari:
        jdbc-url: jdbc:mariadb://localhost:3306/harumarkets?autoReconnect=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: ruby1813!
        driver-class-name: org.mariadb.jdbc.Driver
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt:
  issuer: haru1813@naver.com
  secret_key: haru
  header: Authorization
  active: 10
  refresh: 20
